[metadata.source]
repository_owner = "detekt"
repository_name = "detekt"
repository_url = "https://github.com/detekt/detekt"
code_change_type = "pr"
code_change_id = "5252"
code_change_url = "https://github.com/detekt/detekt/pull/5252"
issue_url = "https://github.com/detekt/detekt/issues/5251"

[verifier]
implemented = false
timeout_sec = 900.0

[agent]
timeout_sec = 1800.0

[environment]
build_timeout_sec = 1800.0
cpus = 4
memory_mb = 10240
allow_internet = true
