[metadata.source]
repository_owner = "Kotlin"
repository_name = "dataframe"
repository_url = "https://github.com/Kotlin/dataframe"
code_change_type = "pr"
code_change_id = "953"
code_change_url = "https://github.com/Kotlin/dataframe/pull/953"
issue_url = "https://github.com/Kotlin/dataframe/issues/690"

[verifier]
implemented = false
timeout_sec = 900.0

[agent]
timeout_sec = 1800.0

[environment]
build_timeout_sec = 1800.0
cpus = 4
memory_mb = 10240
allow_internet = true
