[metadata.source]
repository_owner = "Hannah-Sten"
repository_name = "TeXiFy-IDEA"
repository_url = "https://github.com/Hannah-Sten/TeXiFy-IDEA"
code_change_type = "pr"
code_change_id = "3810"
code_change_url = "https://github.com/Hannah-Sten/TeXiFy-IDEA/pull/3810"
issue_url = "https://github.com/Hannah-Sten/TeXiFy-IDEA/issues/3580"

[verifier]
implemented = false
timeout_sec = 900.0

[agent]
timeout_sec = 1800.0

[environment]
build_timeout_sec = 1800.0
cpus = 4
memory_mb = 10240
allow_internet = true
