[metadata.source]
repository_owner = "square"
repository_name = "okhttp"
repository_url = "https://github.com/square/okhttp"
license = "Apache-2.0"
code_change_type = "pr"
code_change_id = "6887"
code_change_url = "https://github.com/square/okhttp/pull/6887"
issue_url = "https://github.com/square/okhttp/issues/6668"

[verifier]
implemented = false
timeout_sec = 900.0

[agent]
timeout_sec = 1800.0

[environment]
build_timeout_sec = 1800.0
cpus = 4
memory_mb = 10240
allow_internet = true
