[metadata.source]
repository_owner = "ankidroid"
repository_name = "Anki-Android"
repository_url = "https://github.com/ankidroid/Anki-Android"
license = "GPL-3.0"
code_change_type = "pr"
code_change_id = "19661"
code_change_url = "https://github.com/ankidroid/Anki-Android/pull/19661"
issue_url = "https://github.com/ankidroid/Anki-Android/issues/19652"

[verifier]
implemented = false
timeout_sec = 900.0

[agent]
timeout_sec = 1800.0

[environment]
build_timeout_sec = 1800.0
cpus = 4
memory_mb = 10240
allow_internet = true
